### ISSUE TITLE
Where is the attack code?

### ISSUE THREAD

**Issue by ideasplus** [inspire-group/DetectorGuard#1]
Hello, Thanks for your open-source code. 

I want to confirm that did you actually use the generated adversatial example to test the defense algorithm in your experimental part? In the codebase, I can't find the ralated code implementation of localized patch hiding attacks.

I want to use the image with the adversarial patch to test your defense, could you also provide the implementation of patch hiding attacks with different patch locations according to your paper in your codebase?

**Comment by xiangchong1** [comment]
Hi, we do not have code for patch generation in this repo; note that the provable analysis is agnostic to patch generation algorithms.
