### ISSUE TITLE
Bagnet question

### ISSUE THREAD

**Issue by skimtea** [inspire-group/DetectorGuard#2]
Hello,I appreciate that you guys could open your paper source code. There are some questions at below puzzled me when i used your algorithms to defend adversarial patch in some datasets. The officially designed coco dataset cannot be used for image classification tasks; However, you perform image classification of the coco dataset on bagnet, get local_features, and then get the objectness map; So, How do you implement this image classification task firstly? I hope you could help me solve this question. Thank you so much! !

**Comment by xiangchong1** [comment]
See Section 5.1 -> Objectness Predictor -> BagNet-33 for the BagNet training strategy.
See https://github.com/inspire-group/DetectorGuard/tree/main/checkpoints for ad-hoc BagNet training scripts.
