### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by XinDong10** [inspire-group/DetectorGuard#4]
大佬，你的对抗样本（文中提到的500张都是怎么生成的呀），是使用的哪个攻击算法呀，是自己手动生成的嘛？

**Comment by xiangchong1** [comment]
没有用具体的攻击算法，robustness是用certification procedure (algorithm 2)来完成的，得到的结果是对于同一个threat model下的任何攻击算法都适用的。可以再仔细去看一下Section 5.2对certified recall的定义
另外还可以看一下这两个notes
https://github.com/inspire-group/PatchCleanser/blob/main/misc/notes_on_robustness_evaluation.md#are-you-looking-for-attack-code-in-this-repository
https://github.com/inspire-group/adv-patch-paper-list#empirically-robust-defenses-vs-provablycertifiably-robust-defenses

**Comment by XinDong10** [comment]
作者大佬，您好，我看了评估鲁棒性的算法以及您的另一篇objectseeker的文章，在您的这篇文章中，算法二有一个输入x，请问在实际测试certified recall时，您的这个x都是干净图像嘛。既然不需要具体的攻击算法，那您的这个x输入是干净图像嘛，因为没有具体的攻击算法，那么x也就没有办法是一个patch攻击后的对抗样本了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "inspire-group/DetectorGuard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月13日(星期三) 凌晨2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [inspire-group/DetectorGuard] 求助 (Issue #4)





 
没有用具体的攻击算法，robustness是用certification procedure (algorithm 2)来完成的，得到的结果是对于同一个threat model下的任何攻击算法都适用的。可以再仔细去看一下Section 5.2对certified recall的定义
 另外还可以看一下这两个notes
 https://github.com/inspire-group/PatchCleanser/blob/main/misc/notes_on_robustness_evaluation.md#are-you-looking-for-attack-code-in-this-repository
 https://github.com/inspire-group/adv-patch-paper-list#empirically-robust-defenses-vs-provablycertifiably-robust-defenses

**Comment by xiangchong1** [comment]
对的，certification procedure的input一定是一张clean image。
certification结果的意义是，在同一个threat model下的attacker在这张input image上无论怎么加patch ，我们defense是不是能一直都做出正确的prediction。如果input image是一张clean image，这个certification结果很好理解。但是如果input是一张有patch的图片，得到的certification结果的意义是，无论怎么在这张已经有一个patch的图片上加另一个任意的patch，defense能不能做出正确预测，这个结果的意义就不明确了。

**Comment by XinDong10** [comment]
嗯嗯 感谢大佬作者的耐心回复
我看了下object seeker的代码也是先求出脆弱的区域 然后再和patch会存在的区域求逻辑与的结果 然后再统计为1的个数 也就是看看这种位置的patch有多大可能落在脆弱的区域。这个脆弱的区域是用防御算法在干净图像上预测的bm是否满足下界求出的，也就是算法2。





------------------ 原始邮件 ------------------
发件人: Chong Xiang ***@***.***&gt;
发送时间: 2023年9月13日 19:26
收件人: inspire-group/DetectorGuard ***@***.***&gt;
抄送: XinDong10 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [inspire-group/DetectorGuard] 求助 (Issue #4)





 
对的，certification procedure的input一定是一张clean image。
 certification结果的意义是，在同一个threat model下的attacker在这张input image上无论怎么加patch ，我们defense是不是能一直都做出正确的prediction。如果input image是一张clean image，这个certification结果很好理解。但是如果input是一张有patch的图片，得到的certification结果的意义是，无论怎么在这张已经有一个patch的图片上加另一个任意的patch，defense能不能做出正确预测，这个结果的意义就不明确了。
